name: Deploy to GCP

on:
  push:
    branches:
      - main  # Run this workflow when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: SSH into the server and pull the latest code
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /home/deployuser/latest_commit
            git reset --hard origin/main  # Reset local changes
            git pull origin main  # Pull the latest changes
            npm install  # Install dependencies if needed
            pm2 restart app  # Restart your application










