name: Auto-Deploy to GCP

on:
  push:
    branches:
      - main  # Runs only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key and Known Hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.136.91.206 >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Save Commit Info Locally
        run: |
          mkdir -p commit_data
          echo "Commit: ${{ github.sha }}" > commit_data/latest_commit.txt
          echo "Message: ${{ github.event.head_commit.message }}" >> commit_data/latest_commit.txt
          echo "Author: ${{ github.event.head_commit.author.name }}" >> commit_data/latest_commit.txt
          echo "Timestamp: ${{ github.event.head_commit.timestamp }}" >> commit_data/latest_commit.txt
          ls -1 > commit_data/file_list.txt

      - name: Transfer Files to GCP VM
        run: |
          scp -o StrictHostKeyChecking=no -r commit_data deployuser@34.136.91.206:/home/deployuser/latest_commit

      - name: Restart Application (if needed)
        run: |
          ssh -o StrictHostKeyChecking=no deployuser@34.136.91.206 "pm2 restart app || pm2 start app.js --name app"







